draw_set_color(c_black);
draw_set_alpha(0.3);
draw_ellipse(x-sprite_width/2,y-sprite_height/4,x+sprite_width/2,y+sprite_height/4,false);
draw_set_color(c_white);
draw_set_alpha(1);
for(i=0;i<sprite_get_number(sprite_index);i++)
{
	draw_sprite_ext(sprite_index,i,x,y+z-i,image_xscale,image_yscale,image_angle,c_white,1);
}
